server:
  port: 8130 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5t9DebALXE2KZYq5axsp
    keySecret: CwkuUBXMnQznhlmQUvhvzUVRlhVsM7
    bucketName: srb-service-file
